// ─────────────────────────────────────────────
// SWING DNA — Master Data
// All categories, all options, all content.
// Edit this file to update any page content.
// ─────────────────────────────────────────────

export const DNA_CATEGORIES = [
  // ── PHYSICAL DNA ──────────────────────────
  {
    id: 'dexterity',
    section: 'Physical DNA',
    index: '01',
    title: 'Dexterity',
    titleEm: null,
    intro: 'Dexterity establishes which side of the body leads the swing. It determines grip orientation, stance alignment, and all subsequent biometric measurements. Every other selection flows from this foundation.',
    definition: null,
    options: [
      {
        id: 'left-handed',
        label: 'Left Handed',
        color: 'green',
        summary: 'Lead side is right. All references mirror.',
        content: 'The right hand is the lead hand. All grip, stance, and alignment references are mirrored. Lead side is right. Ball position, foot flare, and pivot directions all reference the right side as the target side. Everything in this document mirrors accordingly.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'ambidextrous',
        label: 'Ambidextrous',
        color: 'gold',
        summary: 'Neither side dominates neurologically.',
        content: 'Rare — roughly 1% of students. Neither side dominates neurologically. These students may swing equally well from either side, or show hybrid tendencies. Assess by having them throw, write, and hit — look for consistency. Coach to whichever side shows the more natural athletic pattern.',
        drills: [],
        pros: [],
        warnings: ['For ambidextrous students, run all standard biometric tests from both sides before committing to a dominant side.'],
      },
      {
        id: 'right-handed',
        label: 'Right Handed',
        color: 'green',
        summary: 'Lead side is left. All standard references apply.',
        content: 'The left hand is the lead hand. Lead side is left. All standard references — ball position at left ear, lead foot open, lead hip pivot — apply directly. The vast majority of students fall here. All default language in this document assumes right-handed.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: 'For left-handed students, mirror every directional cue in every other page. "Open your lead foot" means open the right foot. "Left ear ball position" becomes right ear.',
  },

  {
    id: 'eye-dominance',
    section: 'Physical DNA',
    index: '02',
    title: 'Eye',
    titleEm: 'Dominance',
    intro: 'Eye dominance influences how the student perceives the ball, target line, and club face at address. It directly affects head position, pre-shot alignment routine, and the natural tendency to open or close the stance.',
    definition: 'Eye dominance is the eye that provides the brain with more information. Test with the Miles Test: extend arms, form a triangle, center a distant object, then close each eye alternately. The eye that keeps the object centered is dominant.',
    options: [
      {
        id: 'left-eye',
        label: 'Left Eye Dominant',
        color: 'green',
        summary: 'Non-lead eye dominant. Natural head tilt to trail side.',
        content: 'For right-handed players, the non-lead eye is dominant. This creates a natural tendency to tilt the head slightly toward the trail side to give the dominant eye a better view of the ball. Allow and reinforce this — it\'s neurologically natural. Do not force a "level head."',
        drills: [],
        pros: [],
        warnings: ['Never force a left-eye-dominant right-handed player to keep a "perfectly level" head at address. Their natural head tilt is a neurological preference, not a fault.'],
      },
      {
        id: 'right-eye',
        label: 'Right Eye Dominant',
        color: 'green',
        summary: 'Lead eye dominant. Natural square head position.',
        content: 'For right-handed players, the lead eye is dominant. These students tend to set up more square, with the head level or slightly turned toward the target. Their ball-tracking during the swing is more natural. Pre-shot routine should emphasize looking at the target with the lead eye before addressing.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'binocular',
        label: 'Binocular',
        color: 'gold',
        summary: 'Both eyes contribute equally. Maximum flexibility.',
        content: 'Neither eye dominates. Both eyes contribute equally. These students tend to have the most flexibility in head position and often prefer a slightly more face-on head turn. They may benefit from experimenting with both left and right eye targeting cues to find best depth perception.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: 'Eye dominance determines the optimal last-look direction before pulling the trigger. Always confirm before finalizing pre-shot routine.',
  },

  {
    id: 'span-track',
    section: 'Physical DNA',
    index: '03',
    title: 'Span',
    titleEm: 'Track',
    intro: 'The relationship between arm span and standing height is the single most influential biometric in determining natural swing plane, club path tendency, and optimal delivery angle. Get this right and half the battle is won.',
    definition: 'Span is measured fingertip to fingertip with arms outstretched horizontally. Compare to standing height. Span > Height = High Track. Span = Height = Mid Track. Span < Height = Low Track. The direction and magnitude of the differential determines the natural swing orbit.',
    options: [
      {
        id: 'high-track',
        label: 'High Track',
        sublabel: 'Span > Height',
        color: 'green',
        summary: 'Flat, around-the-body arc. Natural draw. Inside path.',
        content: 'Arms longer than torso — swings on a flatter, more around-the-body arc. The club wants to travel on a shallower plane. High Track players naturally create more arc width, which translates directly into clubhead speed when sequencing is correct. Natural inside path, strong draw tendency.',
        drills: [
          { title: 'Wall Plane Drill', body: 'Stand with trail shoulder near a wall. Make a backswing — the club should NOT hit the wall. Confirms the correct flat plane.' },
          { title: 'Hula Hoop Visualization', body: 'Imagine a hula hoop tilted around your body nearly horizontal. Every swing should trace the inside of that hoop.' },
          { title: 'Alignment Stick Plane Drill', body: 'Attach an alignment stick to the grip pointing behind. At the top, the stick angle should nearly match spine angle — flat.' },
        ],
        pros: ['Dustin Johnson', 'Bubba Watson', 'Phil Mickelson', 'Ernie Els'],
        warnings: ['High Track players coached with Low Track instruction (upright, steep) will fight an over-the-top path. A flat arc is not a flaw — it is their natural, most powerful pattern.'],
      },
      {
        id: 'mid-track',
        label: 'Mid Track',
        sublabel: 'Span = Height',
        color: 'gold',
        summary: 'Neutral plane. Balanced proportions. Widest flexibility.',
        content: 'Balanced proportions produce a neutral swing plane. Mid Track students have the widest flexibility in style — they can adopt elements from both high and low profiles effectively. Neither a flat nor steep bias is forced.',
        drills: [
          { title: 'Neutral Plane Check', body: 'At P6 (shaft parallel), shaft should bisect the trail shoulder. This is the universal neutral check for Mid Track players.' },
        ],
        pros: ['Tiger Woods', 'Adam Scott', 'Justin Rose', 'Rory McIlroy'],
        warnings: [],
      },
      {
        id: 'low-track',
        label: 'Low Track',
        sublabel: 'Span < Height',
        color: 'green',
        summary: 'Upright arc. Outside-in tendency. Benefits from shallowing.',
        content: 'Torso longer than arms — swings on a more upright, steeper plane. Natural outside-in tendency. Must guard against steep chops. Benefits from active shallowing moves in transition. Often produces a fade or straight ball flight when correctly managed.',
        drills: [
          { title: 'Shallowing Slot Drill', body: 'Feel the trail elbow drop toward the trail hip in transition. This actively fights the steep tendency and creates the shallow delivery Low Track players need.' },
          { title: 'Headcover Under Arm Drill', body: 'Place a headcover under the trail armpit. Keep it there from P6 to impact. Trains the connected, shallow delivery.' },
        ],
        pros: ['Ben Hogan', 'Lee Trevino', 'Jon Rahm', 'Zach Johnson'],
        warnings: ['Applying High Track instruction (flat, around) to a Low Track student creates a severe pull-hook. The track type is fixed — it cannot be trained away.'],
      },
    ],
    instructorNote: 'This is the first measurement to take with every new student. It overrides stylistic preferences entirely.',
  },

  {
    id: 'forearm-screen',
    section: 'Physical DNA',
    index: '04',
    title: 'Forearm',
    titleEm: 'Screen',
    intro: 'The ratio of forearm length to upper arm length determines how the arms fold, hinge, and create width in the swing. It directly influences natural wrist set timing, elbow behavior, and the arc width a student can generate.',
    definition: 'Measure from elbow to wrist (forearm) vs. shoulder to elbow (upper arm). The longer segment is the dominant lever. This ratio is fixed — it cannot be trained or changed. It must be accommodated.',
    options: [
      {
        id: 'forearm-greater',
        label: 'Forearm > Upper Arm',
        color: 'green',
        summary: 'Wider arc. Natural lag. Later, more gradual wrist hinge.',
        content: 'Longer forearm creates a wider takeaway arc and more natural lag. The wrist hinge happens later and more gradually. These players generate leverage through arc width rather than early wrist set. Trail elbow folds more tightly at the top. Strong arc-width players.',
        drills: [],
        pros: [],
        warnings: ['Telling a long-forearm student to "set the wrists early" or to create a narrow takeaway removes their natural power advantage.'],
      },
      {
        id: 'forearm-equal',
        label: 'Forearm = Upper Arm',
        color: 'gold',
        summary: 'Balanced levers. Most versatile arm action.',
        content: 'Balanced levers produce the most versatile arm action. These students can adapt to different wrist set timings and hinge styles. Neither early nor late hinge is forced. Offer the widest instructional options of all three profiles.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'forearm-less',
        label: 'Forearm < Upper Arm',
        color: 'green',
        summary: 'Earlier hinge. More acute wrist angles. Narrow but loaded.',
        content: 'Shorter forearm, longer upper arm. These players naturally hinge the wrists earlier in the takeaway to create lag. The arc can appear narrower but the wrist angles are more acute. Early wrist set is not a fault for this profile — it is their natural and correct pattern.',
        drills: [],
        pros: [],
        warnings: ['Forcing a wide, one-piece takeaway on this profile causes a flat shoulder turn and loss of lag — the opposite of the intended correction.'],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'lower-body-pivot',
    section: 'Physical DNA',
    index: '05',
    title: 'Lower Body',
    titleEm: 'Pivot',
    intro: 'The lower body pivot type defines the rotational axis of the downswing and is determined by the lower body differential measurement. This is the engine — getting the pivot wrong means maximum power is never achieved regardless of arm skill.',
    definition: 'Lower body differential = the measurement difference between hip and shoulder width. Students >45 use Lead Hip. Students at exactly 45 can use Lead Hip or Pelvis. Students <45 use Rear Hip. This is anatomically determined.',
    options: [
      {
        id: 'lead-hip',
        label: 'Lead Hip',
        sublabel: 'Differential ≥45',
        color: 'green',
        summary: 'Left hip is the fixed axis. Rotation around it.',
        content: 'Left hip is the axis. Stays relatively fixed as the pelvis rotates around it. Creates a powerful rotational base without excessive lateral slide. Critical pairing: lead foot must be open 10–20° to allow full clearance. The most common pivot for High Track students.',
        drills: [
          { title: 'Post Drill', body: 'Feel the lead hip as an immovable post. Everything rotates around it. The hip does not slide left — it turns in place.' },
          { title: 'Lead Hip Hold', body: 'At the top of backswing, pause and feel the lead hip has not moved laterally. Only if it\'s fixed can the rotation accelerate through it.' },
        ],
        pros: ['Dustin Johnson', 'Rory McIlroy', 'Justin Thomas'],
        warnings: ['Lead Hip pivot players with a square lead foot have their most powerful move physically blocked. Always pair with open lead foot.'],
      },
      {
        id: 'pelvis',
        label: 'Pelvis',
        sublabel: 'Differential =45',
        color: 'gold',
        summary: 'Both hips rotate through center equally.',
        content: 'Both hips rotate equally through a central point. Balanced pattern — neither hip dominates. Creates a more "spinning" rotation feel. Most versatile pivot — works with Square or Open stance orientations.',
        drills: [],
        pros: ['Tiger Woods', 'Adam Scott'],
        warnings: [],
      },
      {
        id: 'rear-hip',
        label: 'Rear Hip',
        sublabel: 'Differential <45',
        color: 'green',
        summary: 'Trail hip drives through. Natural lateral bump.',
        content: 'Trail hip drives through and becomes the pivot point. Creates a more lateral "bump" feel in transition. These players naturally shift before turning. Requires an equally strong push-off and lateral return. Often associated with High Pressure Shift (>85%).',
        drills: [
          { title: 'Step Drill', body: 'Start with feet together. Step the lead foot toward target during the swing. Exaggerates the natural lateral pattern Rear Hip players rely on.' },
        ],
        pros: ['Ben Hogan', 'Lee Trevino'],
        warnings: ['Rear Hip students told to "keep their lead hip back" are fighting their DNA. This eliminates their natural power move entirely.'],
      },
    ],
    instructorNote: 'Pivot type and foot flare are inseparably linked. Never prescribe one without confirming the other.',
  },

  {
    id: 'trail-arm',
    section: 'Physical DNA',
    index: '06',
    title: 'Trail Arm',
    titleEm: 'Action',
    intro: 'How the trail arm works relative to the lead arm during the swing. This determines attack angle, depth of the club in the backswing, and natural path direction at impact. Determined by forearm screen and span track combined.',
    definition: null,
    options: [
      {
        id: 'on-top',
        label: 'On Top',
        color: 'green',
        summary: 'Over lead arm. Steeper attack. Fade tendency.',
        content: 'Trail arm works over the lead arm at address and through the swing. Creates a steeper attack angle and naturally promotes a cutting, left-to-right flight. Often associated with Low Track players. The trail elbow points away from the body more in the backswing.',
        drills: [],
        pros: ['Lee Trevino', 'Corey Pavin'],
        warnings: [],
      },
      {
        id: 'side-on',
        label: 'Side On',
        color: 'green',
        summary: 'Same plane as lead arm. Neutral path.',
        content: 'Trail arm and lead arm work in the same plane — side by side. Neutral path. Creates versatility in shot shaping. Promotes a square attack angle. The trail elbow points straight down in the backswing. Often seen in Mid Track students.',
        drills: [],
        pros: ['Tiger Woods', 'Adam Scott'],
        warnings: [],
      },
      {
        id: 'side-under',
        label: 'Side Under',
        color: 'green',
        summary: 'Under lead arm. Shallower attack. Natural draw.',
        content: 'Trail arm works under the lead arm throughout the swing. Creates a shallower attack angle and inside path. Promotes a draw flight naturally. Trail elbow stays connected to the trail hip in the downswing. Ideal for High Track players. The most powerful pattern when matched to the correct track.',
        drills: [
          { title: 'Elbow Pocket Drill', body: 'Hold a glove in the trail armpit. Feel the elbow stay connected as it drops to the hip. Releases only at impact.' },
        ],
        pros: ['Dustin Johnson', 'Bubba Watson', 'Phil Mickelson'],
        warnings: [],
      },
      {
        id: 'side-cover',
        label: 'Side Cover',
        color: 'gold',
        summary: 'Covers over ball. Compressing action. Lower flight.',
        content: 'Trail arm covers over the ball slightly through impact. Creates a powerful compressing action. More common in players with a flatter wrist and strong grip. The cover action naturally delofts the club and promotes a lower, more penetrating ball flight.',
        drills: [],
        pros: ['Collin Morikawa', 'Justin Thomas'],
        warnings: [],
      },
      {
        id: 'under',
        label: 'Under',
        color: 'gold',
        summary: 'Maximum shallowing. Extreme inside delivery.',
        content: 'The most extreme under action — trail arm fully works beneath the plane. Creates the maximum shallowing effect. Often produces a very strong hook if the face is not managed. These players must have a complementary face control mechanism. Rare but powerful when correctly paired.',
        drills: [],
        pros: [],
        warnings: ['Must be paired with a strong grip (V at chin) and active lead side rotation. Without face control, this pattern produces severe hooks.'],
      },
    ],
    instructorNote: 'Arm action and track type MUST align. High Track → Side Under or Under. Low Track → On Top or Side On.',
  },

  // ── SETUP ──────────────────────────────────
  {
    id: 'ball-position',
    section: 'Setup',
    index: '01',
    title: 'Ball',
    titleEm: 'Position',
    intro: 'Ball position (irons) is relative to a landmark on the student\'s face and changes based on their swing arc\'s lowest point — which is determined by pivot type and track. Getting this wrong is the fastest way to create inconsistent contact.',
    definition: 'Ball position is the horizontal location of the ball relative to a spot on the face — defined by the line up from the ball to a facial landmark. This is set BEFORE feet are placed, as part of the pre-shot routine.',
    options: [
      {
        id: 'left-ear',
        label: 'Ball Ahead of Center',
        sublabel: 'Left Ear',
        color: 'green',
        summary: 'Lead Hip + High Track players. Forward in stance.',
        content: 'For players with a Lead Hip pivot and High Track arc. The club reaches its lowest point slightly later (more forward) in the stance. Ball forward of center ensures descending contact at the correct moment. Most common position for draw-biased High Track players.',
        drills: [
          { title: 'Alignment Stick Reference', body: 'Place a stick on the ground pointing at your left ear. Every iron session, confirm ball position before starting.' },
          { title: 'Divot Location Check', body: 'After each iron shot, check divot start location. Divot starting just ahead of ball = correct arc low point.' },
        ],
        pros: [],
        warnings: [],
      },
      {
        id: 'left-cheek',
        label: 'Just Ahead of Middle',
        sublabel: 'Left Cheek',
        color: 'gold',
        summary: 'Mid Track + Pelvis pivot. Slight sweep.',
        content: 'Mid Track and Pelvis pivot players. The arc bottoms out near the center of the stance, making a slightly forward ball position optimal. Provides a shallower descending angle — suits players who prefer to sweep rather than compress.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'nose',
        label: 'Middle',
        sublabel: 'On Nose / Center',
        color: 'green',
        summary: 'Rear Hip + Low Track. Arc bottoms at center.',
        content: 'Rear Hip pivot players and some Low Track players whose arc bottoms out exactly at the center. Any further forward and they hit thin shots. Any further back and they catch it heavy. For these students, center is not a compromise — it is the precise correct position.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'grip-v',
    section: 'Setup',
    index: '02',
    title: 'Lead Hand',
    titleEm: 'Grip V',
    intro: 'The V formed by the thumb and forefinger of the lead hand points at a specific reference on the body. This determines forearm rotation at address, the natural face angle through impact, and the student\'s draw or fade tendency.',
    definition: 'With the lead hand placed on the grip, look down and find the V formed between the thumb and index finger. The direction this V points determines grip strength — and therefore the forearm\'s rotational preset at address.',
    options: [
      {
        id: 'outside-shoulder',
        label: 'Outside of Shoulder',
        sublabel: 'Weak Grip',
        color: 'green',
        summary: 'Weak. Reduces forearm rotation. Fade bias.',
        content: 'V points outside the lead shoulder. Creates a weaker grip position with the lead hand. Reduces forearm rotation through impact, promoting an open face and fade tendency. Best suited for On Top trail arm players and Low Track students who need a more upright, cut-biased delivery.',
        drills: [],
        pros: ['Collin Morikawa', 'Jordan Spieth'],
        warnings: [],
      },
      {
        id: 'inside-shoulder',
        label: 'Inside of Shoulder',
        sublabel: 'Neutral / Strong',
        color: 'green',
        summary: 'Neutral. Versatile. Works with draw and fade.',
        content: 'V points inside the lead shoulder. The most versatile grip position. Provides a neutral forearm preset that works with both draw and fade intentions. Recommended for Side Under arm action players (High Track). Prevents excessive cupping at the top of the backswing.',
        drills: [
          { title: 'Mirror V Check', body: 'Stand at a full-length mirror. Place lead hand on grip, look — the V should point inside the lead shoulder. Adjust until automatic.' },
        ],
        pros: ['Rory McIlroy', 'Jon Rahm', 'Dustin Johnson'],
        warnings: [],
      },
      {
        id: 'at-chin',
        label: 'At Your Chin',
        sublabel: 'Strong Grip',
        color: 'gold',
        summary: 'Strong. Maximum forearm rotation. Draw bias.',
        content: 'V points at or near the chin. Creates the strongest grip position with maximum forearm rotation preset. Promotes a closed face through impact and strong draw tendency. Correct for Under arm action players and High Track students who need maximum release.',
        drills: [],
        pros: ['Zach Johnson', 'Bernhard Langer'],
        warnings: ['Not appropriate for fade players or anyone with an On Top arm action. Creates a smother hook when mismatched.'],
      },
    ],
    instructorNote: 'Always verify grip V before diagnosing any other fault. A grip problem cannot be solved by swing changes.',
  },

  {
    id: 'lead-thumb',
    section: 'Setup',
    index: '03',
    title: 'Lead Thumb',
    titleEm: 'Wrist Set',
    intro: 'The length of the lead thumb on the grip — short, mid, or long — directly controls when the wrists hinge during the takeaway. This is the most overlooked grip element and has massive implications for lag, width, and transition feel.',
    definition: 'A "short" thumb means the lead thumb presses down more firmly on top of the grip — triggering an earlier natural hinge. A "long" thumb extends further down the shaft, delaying the hinge point and promoting a wider, later set.',
    options: [
      {
        id: 'short-thumb',
        label: 'Short',
        sublabel: 'Early Set',
        color: 'green',
        summary: 'Wrists hinge early. Suits High Track. More lag.',
        content: 'Wrists hinge early in the takeaway — before the hands reach hip height. Creates more wrist angle earlier, which suits High Track players who need the wrist load to occur before the arms swing around the body. Promotes a "cocked" feeling at P3. Ideal for players who struggle to maintain lag.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'mid-thumb',
        label: 'Mid',
        sublabel: 'Mid Set',
        color: 'gold',
        summary: 'Wrists hinge at hip height. Most versatile.',
        content: 'Wrists hinge as the hands approach hip height. The most common and versatile position. Works across all track types. Students who feel comfortable here should stay here — only move to short or long if a specific lag or width problem needs addressing.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'long-thumb',
        label: 'Long',
        sublabel: 'Late Set',
        color: 'green',
        summary: 'Wrists hinge late. Wider takeaway. Low Track ideal.',
        content: 'Wrists delay their hinge until hands are near shoulder height or above. Creates a wider, one-piece takeaway feel. Ideal for Low Track players who need maximum width to compensate for a steeper plane. Also beneficial for players who overtuck the trail elbow too early.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'pressure-feet',
    section: 'Setup',
    index: '04',
    title: 'Pressure',
    titleEm: 'in Feet',
    intro: 'Where in the foot the student loads their weight at address determines club plane during setup and dictates how weight shifts dynamically in the swing. Pressure position is connected to power source type.',
    definition: 'Pressure in the feet means where in the foot the center of mass sits at address — not which foot has more weight, but WHERE in the foot: balls, mid-arch, or heel. This affects hip height, spine angle, and the ability to push off the ground.',
    options: [
      {
        id: 'balls-feet',
        label: 'Balls of Feet',
        color: 'green',
        summary: 'Athletic, forward-leaning. Launch players.',
        content: 'Weight forward in the feet — on the balls, not the heels. Creates a slightly more athletic, forward-leaning posture. Ideal for Launch (vertical) power source players because it pre-loads the ground for the explosive upward push. Maintains spine angle through the swing.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'behind-balls',
        label: 'Behind Balls of Feet',
        color: 'gold',
        summary: 'Sit-back posture. Spin players. Hip depth.',
        content: 'Weight sits between the ball of the foot and mid-arch. Creates a slightly more sit-back posture. Suits Spin (torque) power source players who need hip depth in the backswing. Promotes deeper hip socket rotation.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'centered',
        label: 'Centered / Flat',
        color: 'green',
        summary: 'Flat-footed. Glide players. Widest stance.',
        content: 'Flat-footed, balanced pressure across the entire foot. Creates the most stable, lowest center of gravity. Common in Glide (horizontal) power source players who slide laterally through the ball. Often benefits from a slightly wider stance.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'foot-flare',
    section: 'Setup',
    index: '05',
    title: 'Foot',
    titleEm: 'Flare',
    intro: 'Foot flare angle directly controls how much the hips can rotate on the backswing and follow-through. It is inseparably linked to the lower body pivot type. Getting foot flare wrong physically blocks the pivot.',
    definition: null,
    options: [
      {
        id: 'lead-open',
        label: 'Lead Open 10–20°',
        sublabel: 'Trail Square',
        color: 'green',
        summary: 'Lead Hip pivot. Max lead hip clearance on downswing.',
        content: 'Open lead foot allows maximum lead hip clearance on the downswing — critical for Lead Hip pivot players. The square trail foot resists over-rotation on the backswing, creating a powerful coil. The asymmetry is intentional and biomechanically correct.',
        drills: [
          { title: 'Tape Flare Drill', body: 'Tape two lines on a mat showing 10–20° open lead foot and square trail foot. Hit 20 balls per session from this exact stance until instinctive.' },
        ],
        pros: [],
        warnings: [],
      },
      {
        id: 'trail-open',
        label: 'Lead Square',
        sublabel: 'Trail Open 10–20°',
        color: 'gold',
        summary: 'Rear Hip pivot. Maximum backswing coil.',
        content: 'Less common — suited to Rear Hip pivot players who need maximum trail-side rotation on the backswing. The open trail foot allows deeper hip socket loading. The square lead foot provides a stable post to push against.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'both-open',
        label: 'Both Open',
        sublabel: '10–20° Each',
        color: 'green',
        summary: 'Pelvis pivot. Maximum rotation both directions.',
        content: 'Both feet flared outward. Creates the maximum rotation in both directions. Common in Pelvis pivot players and older students with hip mobility restrictions. Reduces coil resistance on the backswing and increases follow-through freedom.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: 'A Lead Hip pivot player with a square lead foot has their most powerful move physically blocked. Always check foot flare matches pivot type before diagnosing casting or over-the-top.',
  },

  // ── MOTIONS ────────────────────────────────
  {
    id: 'max-pressure',
    section: 'Motions',
    index: '01',
    title: 'Max Pressure',
    titleEm: 'Shift',
    intro: 'How much pressure loads into the trail foot at the top of the backswing determines the depth of the power coil. Too little = reverse pivot. Too much = sway. The correct amount is determined by pivot type and power source.',
    definition: 'Max pressure is measured as a percentage of body weight loaded into the trail foot at the top of the backswing. It is NOT the same as weight shift — pressure can build vertically into the ground without the body swaying laterally.',
    options: [
      {
        id: 'sixty-percent',
        label: 'Max 60%',
        sublabel: 'Into Trail Foot',
        color: 'green',
        summary: 'Lead Hip + Launch players. 60% is the ceiling.',
        content: 'Lead Hip pivot players. The hip stays relatively fixed, so weight doesn\'t transfer far. 60% is the ceiling — not the target. Going beyond causes the lead hip to sway off the ball, which destroys the rotational axis.',
        drills: [
          { title: 'Scale Pressure Drill', body: 'Bathroom scale under trail foot. Take backswing to the top and hold. Read the scale — calibrate to 60% for this profile.' },
          { title: 'Lead Foot Tap Test', body: 'At top of backswing, can the student tap their lead foot without losing balance? A 60% loader can. Quick self-diagnosis tool.' },
        ],
        pros: [],
        warnings: [],
      },
      {
        id: 'seventy-eighty-five',
        label: '70–85%',
        sublabel: 'Into Trail Foot',
        color: 'gold',
        summary: 'Pelvis pivot + Spin players. Deeper transfer.',
        content: 'Pelvis pivot and Spin power source players. A deeper weight transfer creates more hip socket depth and a larger coil. The lateral shift is intentional and must be followed by a precise transition move back to center.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'over-eighty-five',
        label: '>85%',
        sublabel: 'Into Trail Foot',
        color: 'green',
        summary: 'Rear Hip + Glide players. Maximum lateral load.',
        content: 'Rear Hip pivot and Glide power source players. Maximum lateral loading — the trail side fully loads before the transition. These players resemble a baseball player\'s stride. Requires an equally strong push-off and lateral return.',
        drills: [],
        pros: [],
        warnings: ['Getting "stuck" behind the ball at >85% is the most common fault. The lateral return must be as aggressive as the initial load.'],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'elbow',
    section: 'Motions',
    index: '02',
    title: 'Trail Elbow',
    titleEm: 'Position',
    intro: 'Where the trail elbow points at the moment it reaches hip height on the downswing determines the club\'s delivery angle and path. This is one of the most diagnostic checkpoints in the entire swing.',
    definition: 'At the P6 position (shaft parallel to the ground on the downswing), check where the trail elbow points. The elbow direction here predicts the impact position and club path with near-perfect accuracy.',
    options: [
      {
        id: 'behind-hip',
        label: 'Behind Hip',
        sublabel: '"Cover" Position',
        color: 'gold',
        summary: 'Too far inside. Flip or block compensation required.',
        content: 'Trail elbow falls too far behind the body. Creates an overly inside delivery that requires a last-moment flip or face rotation to avoid a block right. Often produces a push-draw that can turn into a snap hook. Usually a compensation for something earlier in the swing.',
        drills: [],
        pros: [],
        warnings: ['This is almost never a cause — it is a symptom of an over-inside takeaway. Fix the takeaway, not the elbow position.'],
      },
      {
        id: 'at-hip',
        label: 'At the Hip',
        sublabel: 'The Slot',
        color: 'green',
        summary: 'Ideal. Club on plane. Face square to arc.',
        content: 'Trail elbow arrives at the hip, pointing directly at it. The ideal position for consistent, powerful delivery. The club is on the correct plane, the face is square to the arc, and impact pressure is maximized. All pivot types benefit from this position.',
        drills: [
          { title: 'Elbow-to-Hip Trace', body: 'In slow motion, feel the trail elbow touch the trail hip as the club descends. Freeze at P6 and confirm alignment in a mirror or video.' },
        ],
        pros: [],
        warnings: [],
      },
      {
        id: 'inside-hip',
        label: 'Inside the Hip',
        sublabel: '"Tight" Position',
        color: 'gold',
        summary: 'Tight. Vertical delivery. Open stance players.',
        content: 'Trail elbow tucks very close to the body and stays in front of the trail hip. Creates a more vertical, upright delivery plane. Naturally suits players who use an open stance and Pelvis pivot. Can produce high, soft shots.',
        drills: [],
        pros: ['Modern tour players who hit up on driver'],
        warnings: [],
      },
    ],
    instructorNote: 'The elbow is a symptom. Fix the cause 3/4 through the backswing and the downswing elbow often corrects itself.',
  },

  {
    id: 'lever-delivery',
    section: 'Motions',
    index: '03',
    title: 'Lever',
    titleEm: 'Delivery',
    intro: 'Lever delivery describes how the student releases the club into and through the impact zone. It is the translation of stored lag energy into clubhead speed — and the pattern is determined by trail arm action and grip V combined.',
    definition: null,
    options: [
      {
        id: 'cover',
        label: 'Cover',
        color: 'gold',
        summary: 'Lead arm covers. Trapping. Lower flight.',
        content: 'The lead arm covers over the ball through impact — the trail arm does NOT fully rotate past the lead arm. Creates a trapping, compressing action. Produces a lower, more penetrating ball flight. Common in "hold-off" players with strong grips and Side Cover arm action.',
        drills: [],
        pros: ['Collin Morikawa', 'Justin Thomas', 'Bryson DeChambeau'],
        warnings: [],
      },
      {
        id: 'corner',
        label: 'Corner',
        color: 'green',
        summary: 'Forearms rotate past each other. Natural draw. High Track.',
        content: 'The club releases around the corner of the arc — the forearms rotate past each other through impact. The natural release for High Track, Side Under players. Produces the classic powerful draw flight. Full forearm rotation generates maximum clubhead speed.',
        drills: [
          { title: 'Forearm Rotation Drill', body: 'In slow motion, feel the trail forearm rotate over the lead forearm through impact. The right arm should end on top after impact. This is the "corner."' },
        ],
        pros: ['Dustin Johnson', 'Bubba Watson', 'Phil Mickelson', 'Ernie Els'],
        warnings: [],
      },
      {
        id: 'extend',
        label: 'Extend',
        color: 'green',
        summary: 'Arms extend down the line. Sweep. Fade/straight.',
        content: 'The arms extend fully down the target line through impact — sometimes called a "push-through" or Hogan release. Creates maximum extension at impact and a shallow, sweeping attack angle. Common in Low Track players with On Top arm action.',
        drills: [],
        pros: ['Ben Hogan', 'Lee Trevino', 'Bruce Lietzke'],
        warnings: ['A High Track player forced to extend loses clubhead speed — their body is set up to deliver a Corner release. Never mix.'],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'stance',
    section: 'Motions',
    index: '04',
    title: 'Stance',
    titleEm: 'Orientation',
    intro: 'Stance orientation (open, square, or closed relative to the target line) is determined by eye dominance, pivot type, and power source. It affects how the student perceives the target at address and hip clearance in both directions.',
    definition: null,
    options: [
      {
        id: 'open-stance',
        label: 'Open Stance',
        color: 'gold',
        summary: 'Feet left of target. Pre-cleared hips. Pelvis pivot.',
        content: 'Feet aligned left of the target line. Creates pre-cleared hips at address — the left hip is already partially out of the way. Ideal for Pelvis pivot players and those with limited hip mobility. Naturally promotes an outside-in swing path if not compensated.',
        drills: [],
        pros: ['Lee Trevino', 'Jack Nicklaus'],
        warnings: ['Open stance students need a strong inside takeaway to neutralize the natural outside-in bias created by the foot alignment.'],
      },
      {
        id: 'square-stance',
        label: 'Square Stance',
        color: 'green',
        summary: 'Parallel to target line. Most neutral. All pivot types.',
        content: 'Feet parallel to the target line. The most neutral, versatile stance. Works for all pivot types when paired with correct foot flare. Does not pre-load any rotational bias. Most appropriate for Lead Hip and Rear Hip pivot players who need full range of motion.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'closed-stance',
        label: 'Closed Stance',
        color: 'green',
        summary: 'Feet right of target. Maximum backswing coil. Draw.',
        content: 'Feet aligned right of the target line. Creates maximum backswing coil room with a built-in resistance on the follow-through side. Encourages a more inside takeaway. Common in players with Rear Hip pivot and those who naturally load deep on the trail side.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'wrist-lever',
    section: 'Motions',
    index: '05',
    title: 'Wrist Lever',
    titleEm: 'Action',
    intro: 'The wrist lever action describes how the wrists hinge in the backswing relative to the swing plane. It controls the club face relationship to the swing arc in the backswing — and determines how much face management is needed on the way down.',
    definition: 'Wrist lever action is determined by how the lead wrist hinges: horizontally (ulnar deviation only), diagonally (combination), or vertically (wrist cup/extension). Each creates a different club face angle at the top of the backswing.',
    options: [
      {
        id: 'diagonal',
        label: 'Diagonal / Angled',
        color: 'gold',
        summary: 'Combination hinge. Versatile. Pelvis pivot players.',
        content: 'A combination of ulnar deviation and some wrist bow or cup. Creates a face angle between horizontal and vertical at the top. Versatile — used by many modern players. The most common pattern in Pelvis pivot students.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'horizontal',
        label: 'Horizontal',
        color: 'green',
        summary: 'Pure ulnar deviation. Square face at top. High Track.',
        content: 'Pure ulnar deviation — the wrist hinges along the horizontal plane. Creates a square-to-slightly-closed face at the top of the backswing. The natural hinge for Side Under arm action and Corner delivery players (High Track). Very little face rotation is needed on the way down.',
        drills: [],
        pros: ['Dustin Johnson', 'Jon Rahm'],
        warnings: [],
      },
      {
        id: 'vertical',
        label: 'Vertical',
        color: 'green',
        summary: 'Lead wrist cups. Open face at top. Must close on way down.',
        content: 'The lead wrist cups or extends upward — pure vertical hinge. Creates an open face at the top that must be "closed" on the downswing. Used intentionally by Cover delivery and Extend release players (Low Track). Requires a specific grip and elbow action to match.',
        drills: [],
        pros: ['Ben Hogan', 'Lee Trevino'],
        warnings: [],
      },
    ],
    instructorNote: null,
  },

  {
    id: 'delivery-plane',
    section: 'Motions',
    index: '06',
    title: 'Delivery',
    titleEm: 'Plane',
    intro: 'The delivery plane is the single element of the swing that CANNOT be changed. It is 100% determined by anatomy. At impact, extending the shaft will always point to the same location on the body — fixed by the student\'s proportions and pivot type.',
    definition: 'At impact, if you extend the shaft line, it will point to: upper body/sternum (steeper), midsection (mid), or lower body/belt (shallower). Determined by span track, pivot type, and arm structure. Cannot be trained away.',
    options: [
      {
        id: 'sternum',
        label: 'Upper Body',
        sublabel: 'Shaft → Sternum',
        color: 'green',
        summary: 'High Track + Lead Hip. Steepest plane. Descending irons.',
        content: 'The steepest of the three delivery planes. Associated with High Track and Lead Hip pivot. The shaft points at the upper chest at impact. Corner and Cover release patterns both deliver to this plane. Produces a powerful descending angle with irons.',
        drills: [
          { title: 'Shaft-to-Sternum Impact Drill', body: 'At impact, freeze and hold position. Have someone extend an alignment stick along the shaft. It should point at the sternum. Practice slow-motion holds.' },
        ],
        pros: [],
        warnings: ['A sternum-plane student trying to deliver to belt height will always find the club migrating back to sternum. Never fight it.'],
      },
      {
        id: 'midsection',
        label: 'Mid-Core',
        sublabel: 'Shaft → Midsection',
        color: 'gold',
        summary: 'Mid Track + Pelvis. Neutral plane. Most versatile.',
        content: 'The middle delivery plane — shaft points at the navel or lower abdomen. Associated with Mid Track and Pelvis pivot. Most versatile plane — can work with all release types. The "neutral" delivery used by the largest group of consistent ball-strikers on tour.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'belt',
        label: 'Lower Body',
        sublabel: 'Shaft → Belt',
        color: 'green',
        summary: 'Low Track + Rear Hip. Shallowest. Sweeping contact.',
        content: 'The shallowest delivery plane. Shaft points at the belt or hips at impact. Associated with Low Track and Rear Hip pivot. Creates the longest, most sweeping contact. Requires an Extend release to work correctly. Produces very low dynamic loft and a penetrating ball flight.',
        drills: [],
        pros: ['Ben Hogan', 'Lee Trevino'],
        warnings: [],
      },
    ],
    instructorNote: 'The one rule that overrides all others: the delivery plane CANNOT be changed. Build the entire swing around it.',
  },

  // ── POWER SOURCE ───────────────────────────
  {
    id: 'ground-forces',
    section: 'Power Source',
    index: '01',
    title: 'Kinetic',
    titleEm: 'Ground Forces',
    intro: 'There are three fundamentally different ways golfers generate power from the ground. Each is equally capable of producing elite speed — but they are NOT interchangeable. Training the wrong power type significantly reduces output.',
    definition: 'Ground forces describes the direction and timing of force applied against the ground to generate swing speed. Launch = vertical (jump). Spin = rotational (spin in place). Glide = horizontal (push laterally). Each requires different body geometry.',
    options: [
      {
        id: 'launch',
        label: 'Launch',
        sublabel: 'Vertical Force',
        color: 'green',
        summary: 'Push down → explode up. Trail heel rises early. Tall finish.',
        content: 'Launch force players generate maximum power by driving into the ground and then explosively extending through the hips and legs. The trail heel rises early and aggressively. This is correct — do not try to keep it on the ground. Think of it like a vertical jump.',
        drills: [
          { title: 'Jump Squat Transfer', body: 'Perform a jump squat. Then make a swing using that same downward-load-then-explode-up timing. The ground drive should feel identical.' },
          { title: 'Trail Heel Awareness', body: 'Consciously lift the trail heel early in the downswing (earlier than feels natural). Feel the vertical force push the body upward through impact.' },
        ],
        pros: ['Rory McIlroy', 'Scottie Scheffler', 'Jon Rahm', 'Justin Thomas'],
        warnings: ['Telling a Launch player to "rotate faster" fights their natural force direction. Focus on vertical load depth and explosive upward drive instead.'],
      },
      {
        id: 'spin',
        label: 'Spin',
        sublabel: 'Torque Force',
        color: 'gold',
        summary: 'Rotate in place. Maximum hip speed. Both feet grounded longer.',
        content: 'Torque-force players generate power through hip rotation speed. Both feet stay on the ground longer. The feet resist while the hips accelerate — torsion creates the power. Think of wringing a wet towel.',
        drills: [
          { title: 'Hip Delay Drill', body: 'Halfway down the downswing, consciously hold the hip rotation for one count, then fire. Trains the hands-first, THEN hips sequence.' },
        ],
        pros: ['Tiger Woods', 'Adam Scott', 'Xander Schauffele'],
        warnings: [],
      },
      {
        id: 'glide',
        label: 'Glide',
        sublabel: 'Horizontal Force',
        color: 'green',
        summary: 'Lateral push trail to lead. Mass transfer is the engine.',
        content: 'Horizontal-force players shift their center of mass laterally from trail to lead through the ball. The horizontal transfer of mass is the power engine — rotation follows the shift. These players often have the widest stance and most visible lateral motion.',
        drills: [
          { title: 'Step Drill', body: 'Start with feet together. Take a backswing and step the lead foot toward the target during the swing. Exaggerates the lateral shift timing.' },
        ],
        pros: ['Ben Hogan', 'Retief Goosen'],
        warnings: ['For a Launch player, excessive lateral movement kills vertical energy. The fix is never more lateral — it\'s better sequencing of the vertical load.'],
      },
    ],
    instructorNote: 'Power = Correct Type × Correct Trigger Timing × Correct Pressure Shift. All three must align.',
  },

  {
    id: 'ground-force-sequence',
    section: 'Power Source',
    index: '02',
    title: 'Ground Force',
    titleEm: 'Sequence',
    intro: 'The ground force sequence defines WHEN to initiate the primary power move — the specific moment in the downswing when maximum force should be applied to the ground. The trigger point is different for every power source type.',
    definition: null,
    options: [
      {
        id: 'shaft-level',
        label: 'Launch Trigger',
        sublabel: 'Shaft Level to Ground',
        color: 'green',
        summary: 'Fire when shaft reaches parallel. Earlier than expected.',
        content: 'For Launch (Vertical) players, initiate the maximum push-off when the shaft reaches parallel to the ground on the downswing (P5/P6 position). This is earlier than most students expect. The early ground drive creates vertical energy that peaks exactly at impact.',
        drills: [
          { title: 'Shaft-Tap Drill', body: 'Have student call out "NOW" when they feel the shaft reach parallel on the downswing. That\'s when to fire the ground. Do in slow motion until instinctive.' },
        ],
        pros: [],
        warnings: [],
      },
      {
        id: 'hands-hips',
        label: 'Spin Trigger',
        sublabel: 'Hands Get to Hips',
        color: 'gold',
        summary: 'Fire when hands reach hip height. Maximize coil first.',
        content: 'For Spin (Torque) players, maximum hip rotation accelerates when the hands drop to hip height. The transition sequence is: trail shoulder drops → hands fall → when hands reach hips, fire the hips as fast as possible. Firing too early kills the coil advantage.',
        drills: [],
        pros: [],
        warnings: [],
      },
      {
        id: 'lead-arm-level',
        label: 'Glide Trigger',
        sublabel: 'Lead Arm Level to Ground',
        color: 'green',
        summary: 'Shift begins before backswing completes. Bump and go.',
        content: 'For Glide (Horizontal) players, the maximum lateral shift initiates when the lead arm reaches parallel to the ground in the backswing — before the backswing is fully complete. The shift starts slightly before the backswing ends. This "bump and go" sequencing is the defining characteristic.',
        drills: [],
        pros: [],
        warnings: [],
      },
    ],
    instructorNote: null,
  },
];

// ─────────────────────────────────────────────
// Lookup helpers
// ─────────────────────────────────────────────
export const getCategoryById = (id) =>
  DNA_CATEGORIES.find((c) => c.id === id);

export const getSections = () =>
  [...new Set(DNA_CATEGORIES.map((c) => c.section))];

export const getCategoriesBySection = (section) =>
  DNA_CATEGORIES.filter((c) => c.section === section);
